'use client'
import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import AppProvider from "../components/AppProvider";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import SideNavBar from "@/components/SideNavBar";
import toast, { Toaster } from 'react-hot-toast';
import { ParentFolderContext } from "@/context/ParentFolderContext";
import SearchBar from "@/components/SearchBar";
import { useState } from "react";
import Storage from "@/components/Storage/Storage";

config.autoAddCss = false;

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const[parentFolder, setParentFolder]=useState("")
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppProvider>
          <ParentFolderContext.Provider value={{parentFolder, setParentFolder}}>
            <main className="bg-blue-200 flex">
            <SideNavBar/>
              <div className="grid grid-cols-1 md:grid-cols-3 w-full">
                <div className="col-span-2 p-5">
                  <SearchBar/>
                  {children}
                </div>
                <div className="bg-white p-3">
                  <Storage/>
                </div>
              </div>
            </main>
            <Toaster />

          </ParentFolderContext.Provider>
        </AppProvider>
      </body>
    </html>
  );
}
